name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Projeyi çek
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle izin ver
        run: chmod +x ./gradlew

      - name: APK build
        run: ./gradlew assembleDebug --stacktrace

      - name: APK listele
        run: find . -type f | grep ".apk" || true

      - name: APK dosyalarını yükle
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk
